//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThriftFashionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UerRole
    {
        public int Role_Id { get; set; }
        public Nullable<int> User_Id_fk { get; set; }
        public string RoleName { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
